apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-template.name" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "helm-template.name" . }}
    helm.sh/chart: {{ include "helm-template.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
    - port: 7575
      targetPort: grpc
      protocol: TCP
      name: grpc      
  selector:
    app.kubernetes.io/name: {{ include "helm-template.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
